services:
  gateway:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9051:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - ENV=dev
      - CATALOG_SERVICE_URL=http://catalog:8080
      - IDENTITY_SERVICE_URL=http://identity:8000
      - CART_SERVICE_URL=http://cart:8080
    networks:
      - wassimo-network

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9071:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - ENV=dev
      - CATALOG_SERVICE_URL=http://catalog:8080
      - IDENTITY_SERVICE_URL=http://identity:8000
      - CART_SERVICE_URL=http://cart:8080
    networks:
      - wassimo-network

networks:
  wassimo-network:
    external: true