services:
  gateway:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9051:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - ENV=dev
      - CATALOG_SERVICE_URL=http://app:8080
    networks:
      - wassimo-network

networks:
  wassimo-network:
    external: true